### PR TITLE
Deck 1 Map Changes

### PR DESCRIPTION
**Pull request by Zero-Bits**
super wip, probably doesn't compile, incomplete, but I'm sick rn so I'm out of the action.

### CODE REVIEW

**Comment by Zero-Bits** [comment]
maintainers are allowed to edit this. feel free to make pulls to my branch, etc.

**Comment by MalfunctioningAI** [comment]
It's angry because some areas lack ventilation/an APC.

**Comment by MalfunctioningAI** [comment]
`## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Xenobiology Lab(/area/rnd/xenobiology) lacks an APC.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Xenobiology Lab(/area/rnd/xenobiology) lacks an air scrubber.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Xenobiology Lab(/area/rnd/xenobiology) lacks an air vent.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Xenobiology Access(/area/rnd/xenobiology/entry) lacks an APC.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Xenobiology Access(/area/rnd/xenobiology/entry) lacks an air scrubber.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Xenobiology Access(/area/rnd/xenobiology/entry) lacks an air vent.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research and Development(/area/rnd/research) lacks an APC.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research and Development(/area/rnd/research) lacks an air scrubber.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research and Development(/area/rnd/research) lacks an air vent.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Xenoflora Lab(/area/rnd/xenobiology/xenoflora) lacks an APC.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Xenoflora Lab(/area/rnd/xenobiology/xenoflora) lacks an air scrubber.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Xenoflora Lab(/area/rnd/xenobiology/xenoflora) lacks an air vent.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Miscellaneous Research(/area/rnd/misc_lab) lacks an APC.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Miscellaneous Research(/area/rnd/misc_lab) lacks an air scrubber.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Miscellaneous Research(/area/rnd/misc_lab) lacks an air vent.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Aux Custodial Supplies(/area/rnd/blanks) lacks an APC.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research Locker Room(/area/rnd/locker) lacks an APC.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research Locker Room(/area/rnd/locker) lacks an air scrubber.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research Locker Room(/area/rnd/locker) lacks an air vent.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research Security Checkpoint(/area/rnd/checkpoint) lacks an APC.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research Security Checkpoint(/area/rnd/checkpoint) lacks an air scrubber.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research Security Checkpoint(/area/rnd/checkpoint) lacks an air vent.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research and Development Access(/area/rnd/entry) lacks an APC.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Fabricator Lab(/area/rnd/development) lacks an APC.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Fabricator Lab(/area/rnd/development) lacks an air scrubber.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Fabricator Lab(/area/rnd/development) lacks an air vent.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research Break Room(/area/rnd/breakroom) lacks an APC.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research Break Room(/area/rnd/breakroom) lacks an air scrubber.
## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research Break Room(/area/rnd/breakroom) lacks an air vent.
## UNIT_TEST ##: !!! FAILURE !!! [MAP: Area Test APC / Scrubbers / Vents]: [11/238]Some areas did not have the expected APC/vent/scrubber setup.`

`## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
## UNIT_TEST ##: !!! FAILURE !!! [MAP: Cryopod Validity Check]: Cryopods were not set up correctly.
## UNIT_TEST ##: *** SUCCESS *** [MAP: Camera nil c_tag check]: Have cameras have the c_tag set.
## UNIT_TEST ##: *** SUCCESS *** [MAP: Camera unique c_tag check]: 245 cameras have a unique c_tag.
## UNIT_TEST ##: [MAP: Disposal segments shall connect with other disposal pipes]: Following disposal pipe does not connect correctly: The disposal pipe (/obj/structure/disposalpipe/segment) ([0x2005d38]) (the floor) (90,100,4) (/turf/simulated/floor/tiled/white)
## UNIT_TEST ##: !!! FAILURE !!! [MAP: Disposal segments shall connect with other disposal pipes]: 1 disposal segment did not connect with other disposal pipes.`

`UNIT_TEST ##: !!! FAILURE !!! [ZAS: Xenobiology]: Pressure out of bounds: 0 | Turf: the open space |  Location: 110 // 70 // 4`

**Comment by MalfunctioningAI** [comment]
>\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Xenobiology Lab(/area/rnd/xenobiology) lacks an APC.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Xenobiology Lab(/area/rnd/xenobiology) lacks an air scrubber.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Xenobiology Lab(/area/rnd/xenobiology) lacks an air vent.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Xenobiology Access(/area/rnd/xenobiology/entry) lacks an APC.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Xenobiology Access(/area/rnd/xenobiology/entry) lacks an air scrubber.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Xenobiology Access(/area/rnd/xenobiology/entry) lacks an air vent.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research and Development(/area/rnd/research) lacks an APC.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research and Development(/area/rnd/research) lacks an air scrubber.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research and Development(/area/rnd/research) lacks an air vent.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Xenoflora Lab(/area/rnd/xenobiology/xenoflora) lacks an APC.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Xenoflora Lab(/area/rnd/xenobiology/xenoflora) lacks an air scrubber.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Xenoflora Lab(/area/rnd/xenobiology/xenoflora) lacks an air vent.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Miscellaneous Research(/area/rnd/misc_lab) lacks an APC.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Miscellaneous Research(/area/rnd/misc_lab) lacks an air scrubber.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Miscellaneous Research(/area/rnd/misc_lab) lacks an air vent.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Aux Custodial Supplies(/area/rnd/blanks) lacks an APC.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research Locker Room(/area/rnd/locker) lacks an APC.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research Locker Room(/area/rnd/locker) lacks an air scrubber.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research Locker Room(/area/rnd/locker) lacks an air vent.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research Security Checkpoint(/area/rnd/checkpoint) lacks an APC.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research Security Checkpoint(/area/rnd/checkpoint) lacks an air scrubber.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research Security Checkpoint(/area/rnd/checkpoint) lacks an air vent.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research and Development Access(/area/rnd/entry) lacks an APC.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Fabricator Lab(/area/rnd/development) lacks an APC.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Fabricator Lab(/area/rnd/development) lacks an air scrubber.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Fabricator Lab(/area/rnd/development) lacks an air vent.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research Break Room(/area/rnd/breakroom) lacks an APC.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research Break Room(/area/rnd/breakroom) lacks an air scrubber.
\## UNIT_TEST ##: [MAP: Area Test APC / Scrubbers / Vents]: --------------- Research Break Room(/area/rnd/breakroom) lacks an air vent.
\## UNIT_TEST ##: !!! FAILURE !!! [MAP: Area Test APC / Scrubbers / Vents]: [11/238]Some areas did not have the expected APC/vent/scrubber setup.

>\## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
\## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
\## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
\## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
\## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
\## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
\## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
\## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
\## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
\## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
\## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
\## UNIT_TEST ##: [MAP: Cryopod Validity Check]: The Auxiliary Cryogenic Storage lacks a cryopod control computer while holding a cryopod.
\## UNIT_TEST ##: !!! FAILURE !!! [MAP: Cryopod Validity Check]: Cryopods were not set up correctly.
\## UNIT_TEST ##: *** SUCCESS *** [MAP: Camera nil c_tag check]: Have cameras have the c_tag set.
\## UNIT_TEST ##: *** SUCCESS *** [MAP: Camera unique c_tag check]: 245 cameras have a unique c_tag.
\## UNIT_TEST ##: [MAP: Disposal segments shall connect with other disposal pipes]: Following disposal pipe does not connect correctly: The disposal pipe (/obj/structure/disposalpipe/segment) ([0x2005d38]) (the floor) (90,100,4) (/turf/simulated/floor/tiled/white)
\## UNIT_TEST ##: !!! FAILURE !!! [MAP: Disposal segments shall connect with other disposal pipes]: 1 disposal segment did not connect with other disposal pipes.

>\## UNIT_TEST ##: !!! FAILURE !!! [ZAS: Xenobiology]: Pressure out of bounds: 0 | Turf: the open space |  Location: 110 // 70 // 4

**Comment by Andromeda-K22** [comment]
I'l take a look at this after i finish adding some stuff.

**Comment by Zero-Bits** [comment]
Okay. I kinda borked this one. I'll have to redo it from scratch.

**Pull request closed without merging**
