### PR TITLE
Tweaks subspecies, and fixes gravity-adapted sprites.

### PR DESCRIPTION
**Pull request by MalfunctioningAI**
:cl: MalfunctioningAI
tweak: Gravity-Adapted are now better suited for player hazards, instead of environmental hazards.
tweak: Space-Adapted are now better suited for environmental hazards, instead of player hazards.
/:cl:

### CODE REVIEW

**Comment by MalfunctioningAI** [comment]
Feedback requested. Something feels off about the values.

**Comment by MalfunctioningAI** [comment]
PR is subject to testing later today, and personal feedback will perhaps result in changes.

**Comment by MalfunctioningAI** [comment]
PR is subject to testing later today, and personal feedback from myself might result in changes.

**Comment by MalfunctioningAI** [comment]
#[WORK IN PROGRESS]

**Comment by MalfunctioningAI** [comment]
# [WORK IN PROGRESS]

**Comment by orelbon** [comment]
I think the new values are pretty good.

**Comment by MalfunctioningAI** [comment]
fuck you github you're retarded

**Pull request merged**
